server:
  port: 80

spring:
  application:
    name: cloud-consumersonsul-order
  cloud:
    consul:
      host: 192.168.18.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}